RET_SPEC_ATTR = '_RetSpec'
CALL_SPEC_ATTR = '_CallSpec'

CALL_ARGS_NODE_ID = 'call_args'
CALL_RETS_NODE_ID = 'call_rets'

OBJ_CALL_ARG = 'OBJ_CALL_ARG'
OBJ_CALL_RET = 'OBJ_CALL_RET'
OBJ_CALL_ARGS = OBJ_CALL_ARG,
OBJ_CALL_RETS = OBJ_CALL_RET,
